import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { prefix } from "../config";
import { privateSubnet1, privateSubnet2, rdsSg, redisSg } from "./networking";

const config = new pulumi.Config();

// Infrastructure-managed secret. Always generated by the CLI; used internally
// to compose DATABASE_URL. Not injected as a standalone env var.
export const dbPassword = config.requireSecret("dbPassword");

// User-defined secrets are read from Pulumi config in the same way, e.g.:
// export const mySecret = config.requireSecret("mySecret");

const dbSubnetGroup = new aws.rds.SubnetGroup(`${prefix}-db-subnet`, {
  subnetIds: [privateSubnet1.id, privateSubnet2.id],
  tags: { Name: `${prefix}-db-subnet` },
});

export const db = new aws.rds.Instance(`${prefix}-db`, {
  identifier: `${prefix}-db`,
  engine: "postgres",
  engineVersion: "16.6",
  instanceClass: "db.t4g.small",
  allocatedStorage: 20,
  storageType: "gp3",
  dbName: "example",
  username: "postgres",
  password: dbPassword,
  dbSubnetGroupName: dbSubnetGroup.name,
  vpcSecurityGroupIds: [rdsSg.id],
  publiclyAccessible: false,
  storageEncrypted: true,
  backupRetentionPeriod: 7,
  deletionProtection: true,
  skipFinalSnapshot: false,
  finalSnapshotIdentifier: `${prefix}-db-final-snapshot`,
  tags: { Name: `${prefix}-db` },
}, { ignoreChanges: ["password"] });

const redisSubnetGroup = new aws.elasticache.SubnetGroup(`${prefix}-redis-subnet`, {
  subnetIds: [privateSubnet1.id, privateSubnet2.id],
  tags: { Name: `${prefix}-redis-subnet` },
});

export const redis = new aws.elasticache.Cluster(`${prefix}-redis`, {
  clusterId: `${prefix}-redis`,
  engine: "redis",
  engineVersion: "7.1",
  nodeType: "cache.t4g.small",
  numCacheNodes: 1,
  subnetGroupName: redisSubnetGroup.name,
  securityGroupIds: [redisSg.id],
  tags: { Name: `${prefix}-redis` },
});

export const bucket = new aws.s3.Bucket(`${prefix}-files`, {
  tags: { Name: `${prefix}-files` },
});

new aws.s3.BucketVersioning(`${prefix}-files-versioning`, {
  bucket: bucket.id,
  versioningConfiguration: { status: "Enabled" },
});

new aws.s3.BucketServerSideEncryptionConfiguration(`${prefix}-files-encryption`, {
  bucket: bucket.id,
  rules: [{
    applyServerSideEncryptionByDefault: { sseAlgorithm: "AES256" },
  }],
});

new aws.s3.BucketPublicAccessBlock(`${prefix}-files-block`, {
  bucket: bucket.id,
  blockPublicAcls: true,
  ignorePublicAcls: true,
  blockPublicPolicy: true,
  restrictPublicBuckets: true,
});
